### ISSUE TITLE
[FE] Fix "Projects" tags rendering

### ISSUE THREAD

**Issue by FabrizioContu** [IT-Academy-BCN/ita-profiles-frontend#124]
The component ProjectCard doesn't show Tags details.

**Comment by jordimorillo** [comment]
I want to see the user history when you make new issues. This is:

As <the user role>
We want to <what we want to have>
To do this we will <what you will do to accomplish it>
The issue will be complete when <requirements of completion>

;)

**Comment by FabrizioContu** [comment]
As Front End dev 
we want to show the first two skills of each project.
To do this we will create a mapping function to iterate the "skills" array
The issue will be complete when the code successfully displays the first two skill of each project, separated by a dot.
