### ISSUE TITLE
[FE] Implement user profile creation/editing screen

### ISSUE THREAD

**Issue by vicenlu** [IT-Academy-BCN/ita-profiles-frontend#32]

**Comment by vicenlu** [comment]
![Image](https://github.com/IT-Academy-BCN/ita-profiles-frontend/assets/24873762/9ecf3beb-c2c4-45fa-b3e4-e4a44b060316)

**Comment by jordimorillo** [comment]
@treee97 tienes otras tarjetas mucho más prioritarias que ésta para el sprint. Por ejemplo, si habéis pactado ya el endpoint con backend, se pueden ir desarrollando las tarjetas que enlazan con dichos endpoints confiando en la url pactada.
