### ISSUE TITLE
[FE] Fix select button in the open students list

### ISSUE THREAD

**Issue by jordimorillo** [IT-Academy-BCN/ita-profiles-frontend#46]
Como invitado
Dado que en producción tenemos un listado de estudiantes en el que aparece un cuadro select que en figma no aparece
y queremos que el diseño de nuestra maqueta sea como el diseño de figma
Vamos a quitar ese select porque no se corresponde con figma
Sabremos que ésto se cumple cuando veamos el listado de estudiantes online sin el botón de select

**Comment by llopFilms** [comment]
No trobo cap etiqueta select al layout dels estudiants...  🤔
