### ISSUE TITLE
[FE] Adapt the students list design for mobile phones

### ISSUE THREAD

**Issue by jordimorillo** [IT-Academy-BCN/ita-profiles-frontend#63]
Como visitantes con rol abierto y desde un teléfono móvil (p.ej.: IPhone SE)
Queremos ver el listado de estudiantes con un diseño que guarde coherencia con lo que propone Luis en Figma
Para ello vamos a adaptar el viewport de los estilos para que active el diseño de figma para menos de 600px
Sabremos que esto se cumple cuando visitemos producción con un navegador inspeccionando con un ancho de 600px o menos y veamos un diseño que guarde coherencia con la propuesta de Luis en Figma.

![Image](https://github.com/IT-Academy-BCN/ita-profiles-frontend/assets/11392091/4514c1de-2eee-4d6e-9402-e1934d3516d3)

**Comment by Dar-ya218** [comment]
Not ready yet. I need check still buttons.
