### ISSUE TITLE
[FE] Add a "Datos del bootcamp" component in student detail view

### ISSUE THREAD

**Issue by jordimorillo** [IT-Academy-BCN/ita-profiles-frontend#78]
Como Usuario Open
Queremos ver la parte de "Datos del bootcamp" 
Para ello vamos a maquetar con un componente de react el diseño de figma y lo vamos a colgar
Sabremos que ésto se cumple cuando podamos ver en la web de staging el componente manteniendo la coherencia con el diseño de figma.

---

![Image](https://github.com/IT-Academy-BCN/ita-profiles-frontend/assets/11392091/09186fb2-fedb-42ae-8484-7d777d5af14c)

**Comment by Dar-ya218** [comment]
- [x] Created BootcampComponent keeping coherence with figma desing.

![Image](https://github.com/IT-Academy-BCN/ita-profiles-frontend/assets/123471637/826aad9c-6d10-4f14-8b79-185da9c84688)

-The background colors of UserDetailsContent need to be reviewed on PC and mobile.
